version: '3.8'

services:
  app:
    build:
      context: ./app
    container_name: app_service
    volumes:
      - ./app:/opt/app-root/src/app:rw
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "7420:7420"

  chromadb:
    image: chromadb/chroma
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data/chroma_data:/chroma/chroma

  app-cron:
    container_name: app-cron
    build:
      context: cron
      dockerfile: Dockerfile
    restart: unless-stopped

#  frontend:
#    build:
#      context: ./frontend
#    container_name: frontend_service
#    command: poetry run python gradio
#    volumes:
#      - ./frontend:/frontend
#    environment:
#      - PYTHONUNBUFFERED=1
#      - PORT=7860
#    ports:
#      - "7860:7860"


networks:
  default:
    driver: bridge

volumes:
  chroma-data:
    driver: local